version: "3.8"
services:
  nginx:
    build: ./nginx
    volumes:
      - './project/public:/app/public'
    ports:
      - '3900:80'
    depends_on:
      - app
  app:
    build: ./app
    volumes:
      - './project:/app'
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: talkbank
      POSTGRES_PASSWORD: talkbank
      POSTGRES_USER: talkbank
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - '3901:5432'
  rabbitmq:
    image: rabbitmq:3.6.12-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: talkbank
      RABBITMQ_DEFAULT_PASS: talkbank
    volumes:
      - rm-data:/var/lib/rabbitmq/mnesia
    ports:
        - "3902:5672"
        - "3903:15672"

volumes:
  db-data:
  rm-data:
